version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
      - JENKINS_ARGS="--prefix=/jenkins"
    expose:
      - "8080"
    volumes:
      - ~/jenkins_home:/var/jenkins_home
      - ~/jenkins_home/jenkins.war:/usr/share/jenkins/jenkins.war
      - /var/run/docker.sock:/var/run/docker.sock
  
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: ssam
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  spring-app:
    build: 
      context: ./BACK/Ssam
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ssam?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SERVER_SERVLET_CONTEXT_PATH=/api

  react-app:
    build:
      context: ./FE/Frontend
      dockerfile: Dockerfile
    volumes:
      - react-build:/usr/share/nginx/html

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - react-build:/usr/share/nginx/html
    depends_on:
      - jenkins
      - spring-app
      - react-app

networks:
  app-network:

volumes:
  jenkins_home:
  mysql_data:
  react-build:
