version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
      - JENKINS_ARGS="--prefix=/jenkins"
    expose:
      - "8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  
  spring-app:
    build: 
      context: ./BACK/Ssam
      dockerfile: Dockerfile
    expose:
      - "8081"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ssam?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ssam
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - jenkins
      - spring-app

volumes:
  jenkins_home:
  mysql_data: