version: '3'
    
services:
  spring-app:
    image: ${BACKEND_IMAGE_NAME:-asz2325/backend-image}:${BUILD_NUMBER:-latest}
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SERVER_SERVLET_CONTEXT_PATH=/api
      
  react-app:
    image: ${FRONTEND_IMAGE_NAME:-asz2325/frontend-image}:${BUILD_NUMBER:-latest}
    ports:
      - "3000:3000"
