version: '3'
    
services:
  spring-app:
    build: 
      context: ./BACK/Ssam
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SERVER_SERVLET_CONTEXT_PATH=/api
      
  react-app:
    build:
      context: ./FE/Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
      
