version: '3'

networks:
  default:
    external:
      name: app-network
    
services:
  spring-app:
    build: 
      context: ./BACK/Ssam
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ssam?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SERVER_SERVLET_CONTEXT_PATH=/api
    networks:
      - app-network
    depends_on:
      - mysql
      
  react-app:
    build:
      context: ./FE/Frontend
      dockerfile: Dockerfile
    volumes:
      - react-build:/usr/share/nginx/html
    networks:
      - app-network
      
volumes:
  react-build:
    external: true