version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    
  spring-app:
    build: 
      context: ./BACK/Ssam
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - mysql

  # react-app:
  #   build:
  #     context: ./FRONT/Ssam
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - jenkins
      - spring-app
      # - react-app

volumes:
  jenkins_home:
  mysql_data: