pipeline {
    agent any
    
    environment {
        DOCKER_IMAGE = "backend-image"
        DOCKER_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm // 소스 코드 체크아웃
            }
        }
        
        stage('Build') {
            steps {
                dir('BACK/Ssam') { // Backend 디렉토리로 이동
                    sh './gradlew build' // Gradle을 사용하여 프로젝트 빌드
                }
            }
        }
        
        stage('Docker Build') {
            steps {
                dir('BACK/Ssam') {
                    script {
                        docker.build("${DOCKER_IMAGE}:${DOCKER_TAG}") // Docker 이미지 빌드
                    }
                }
            }
        }
        
        stage('Docker Push') {
            steps {
                script {
                    docker.withRegistry('https://your-docker-registry-url', 'docker-credentials-id') {
                        docker.image("${DOCKER_IMAGE}:${DOCKER_TAG}").push() // Docker 이미지 푸시
                    }
                }
            }
        }
        
        stage('Deploy') {
            steps {
                // 배포 단계 (예: docker-compose를 사용한 서비스 재시작)
                sh 'docker-compose up -d backend'
            }
        }
    }
    
    post {
        always {
            // 빌드 완료 후 Docker 이미지 정리
            sh "docker rmi ${DOCKER_IMAGE}:${DOCKER_TAG}"
        }
    }
}