pipeline {
    agent any
    
    environment {
        DOCKERHUB_CREDENTIALS = credentials('docker-hub-credentials')
        BACKEND_IMAGE_NAME = "asz2325/backend-image"
    }
    
    stages {
        stage('Check Docker') {
            steps {
                script {
                    try {
                        sh 'docker --version'
                    } catch(Exception e) {
                        echo 'ERROR: Docker is not installed or not found in PATH'
                        echo "Caught: ${e}"
                    }
                }
            }
        }
        stage('Clone Repository') {
            steps {
                git branch: 'test',
                credentialsId: 'gitlab-credentials',
                url: "https://lab.ssafy.com/s11-webmobile1-sub2/S11P12E201.git"
            }
        }
        
        stage('Build and Push Backend') {
            steps {
                script {
                    def backendImage = docker.build("${BACKEND_IMAGE_NAME}:${BUILD_NUMBER}")
                    docker.withRegistry('', 'docker-hub-credentials') {
                        backendImage.push()
                    }
                }
            }
        }
        
        stage('Deploy Backend') {
            steps {
                dir('../..') {
                    sh "docker-compose up -d --no-deps --build spring-app"
                }
            }
        }
    }
    
    post {
        always {
            sh "docker logout"
        }
    }
}