version: '3'

networks:
  default:
    external:
      name: app-network

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: ssam
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - react-build:/usr/share/nginx/html
    depends_on:
      - jenkins
    networks:
      - app-network

volumes:
  mysql_data:
    external: true
  react-build:
    external: true
  jenkins_home:
    external: true